const levels=window.LEVELS;let levelIndex=0,found=[],hints=2,timeLeft=90,timerId;
const $=id=>document.getElementById(id),imgA=$("imgA"),imgB=$("imgB"),overlayA=$("overlayA"),overlayB=$("overlayB");
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),1000)}
function update(){ $("progress").textContent=`${found.length} / 7`;$("levelCount").textContent=`${levelIndex+1} / ${levels.length}`;$("hintCount").textContent=hints;$("nextBtn").disabled=found.length<7;$("timer").textContent=timeLeft}
function startTimer(){clearInterval(timerId);timeLeft=90;update();timerId=setInterval(()=>{timeLeft--;update();if(timeLeft<=0){clearInterval(timerId);showModal("時間到","重新挑戰本關","再試一次",false)}},1000)}
function load(){const l=levels[levelIndex];found=[];imgA.src=l.a;imgB.src=l.b;overlayA.innerHTML="";overlayB.innerHTML="";$("levelTitle").textContent=`第 ${levelIndex+1} 關｜${l.title}`;startTimer()}
function point(e,wrap){const r=wrap.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
function hit(e,wrap){const p=point(e,wrap),spots=levels[levelIndex].spots;let best=-1,dist=999;spots.forEach((s,i)=>{if(found.includes(i))return;const d=Math.hypot(p.x-s.x,p.y-s.y);if(d<s.r&&d<dist){best=i;dist=d}});if(best<0){toast("不是這裡");return}found.push(best);draw(best);update();if(found.length===7){clearInterval(timerId);setTimeout(()=>showModal(levelIndex===levels.length-1?"完成全部關卡":"過關",`剩餘 ${timeLeft} 秒`,levelIndex===levels.length-1?"重新開始":"下一關",true),250)}}
function draw(i){const s=levels[levelIndex].spots[i];[overlayA,overlayB].forEach(o=>{const d=document.createElement("div");d.className="spot";d.style.left=s.x*100+"%";d.style.top=s.y*100+"%";d.style.width=s.r*200+"%";d.style.aspectRatio="1";o.appendChild(d)})}
function showModal(t,txt,btn,success){$("modalTitle").textContent=t;$("modalText").textContent=txt;$("modalBtn").textContent=btn;$("modal").classList.add("show");$("modal").dataset.success=success?"1":"0"}
$("topWrap").onclick=e=>hit(e,e.currentTarget);$("bottomWrap").onclick=e=>hit(e,e.currentTarget);
$("hintBtn").onclick=()=>{if(hints<=0){toast("提示已用完");return}const remain=levels[levelIndex].spots.map((_,i)=>i).filter(i=>!found.includes(i));if(!remain.length)return;hints--;const i=remain[Math.floor(Math.random()*remain.length)],s=levels[levelIndex].spots[i];[overlayA,overlayB].forEach(o=>{const d=document.createElement("div");d.className="hintPulse";d.style.left=s.x*100+"%";d.style.top=s.y*100+"%";d.style.width=s.r*240+"%";d.style.aspectRatio="1";o.appendChild(d);setTimeout(()=>d.remove(),1600)});update()}
$("restartBtn").onclick=load;$("nextBtn").onclick=()=>{if(found.length<7)return;levelIndex=(levelIndex+1)%levels.length;load()}
$("modalBtn").onclick=()=>{$("modal").classList.remove("show");if($("modal").dataset.success==="1"){levelIndex=levelIndex===levels.length-1?0:levelIndex+1;if(levelIndex===0)hints=2}load()}
load();